version: '3'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb
    command: "--transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb_read_only_compressed=OFF"
    container_name: nextcloud-db
    restart: always
    volumes:
      - ${BASE_PATH}/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}

  redis:
    image: redis
    container_name: redis
    restart: always

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    ports:
      - "${HTTP_MAPPING}"
      - "${HTTPS_MAPPING}"
    links:
      - db
    volumes:
      - ${BASE_PATH}/nextcloud/config:/var/www/html/config
      - ${BASE_PATH}/nextcloud/data:/var/www/html/data
      - ${BASE_PATH}/nextcloud/apps:/var/www/html/apps
      - ${BASE_PATH}/nextcloud/etc/apache2/:/etc/apache2
      - ${BASE_PATH}/nextcloud/etc/ssl/private:/etc/ssl/private
      - ${BASE_PATH}/nextcloud/etc/php/php.ini-development:/usr/local/etc/php/php.ini-development
      - ${BASE_PATH}/nextcloud/etc/php/php.ini-production:/usr/local/etc/php/php.ini-production
    depends_on:
        - db
        - redis
    restart: always
