version: "3"
services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    container_name: 'gitlab' 
    restart: always
    hostname: '${HOSTNAME}'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url '${EXTERNAL_URL}'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - ${HTTP_PORT}
      - ${HTTPS_PORT}
      - ${SSH_PORT}
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    ulimit:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8192M
        reservations:
          cpus: '0.25'
          memory: 1024M
