version: "3"

# More info at https://checkmk.com/cms_introduction_docker.html/
services:
  checkmk:
    container_name: checkmk
    image: checkmk/check-mk-raw:1.6.0-latest
    ports:
      - "${HTTP_MAPPING}"
    # Volumes store your data between container upgrades
    volumes:
       - '/etc/localtime:/etc/localtime:ro'
       - '${BASE_PATH}/checkmk/etc/htpasswd:/etc/htpasswd'
       - '${BASE_PATH}/checkmk/omd/sites:/omd/sites'
    restart: always
